FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow==3.1.0

RUN mkdir -p /app/local/mlflow /app/local/mlartifacts

ENV MLFLOW_BACKEND_STORE_URI=sqlite:////app/local/mlflow/mlflow.db
ENV MLFLOW_ARTIFACT_ROOT=/app/local/mlartifacts

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:////app/local/mlflow/mlflow.db", \
     "--artifact-root", "/app/local/mlartifacts", \
     "--host", "0.0.0.0", "--port", "5000"]
